import {
  BiHomeAlt,
  BiInfoCircle,
  BiUserCircle,
  BiCabinet,
  BiMessage,
  BiImages,
  BiBookOpen,
  BiBriefcase,
  BiGroup,
  BiQuestionMark,
  BiStar,
  BiBasket,
  BiNews,
} from "react-icons/bi";

export const navIcons = {
  home: <BiHomeAlt />,
  profile: <BiUserCircle />,
  about: <BiInfoCircle />,
  services: <BiCabinet />,
  contact: <BiMessage />,
  gallery: <BiImages />,
  blog: <BiBookOpen />,
  portfolio: <BiBriefcase />,
  team: <BiGroup />,
  faq: <BiQuestionMark />,
  testimonials: <BiStar />,
  projects: <BiBriefcase />,
  events: <BiStar />,
  shop: <BiBasket />,
  news: <BiNews />,
};
